import streamlit as st
import requests

# Set page config for a widescreen layout
st.set_page_config(
    page_title="OrthoAssist AI",
    layout="wide",
    initial_sidebar_state="expanded"
)

# App Title & Subtitle
st.title(" OrthoAssist: Vision & Prescription Validator")
st.caption("An intelligent decision-support tool for orthopedic radiologists and surgeons.")
st.markdown("---")

# Layout Configuration: 2 Columns
col1, col2 = st.columns([1, 1.2])

with col1:
    st.subheader("📋 Case Input Panel")
    
    # 1. File Uploader for X-Ray
    uploaded_file = st.file_uploader(
        "Upload Patient X-Ray (JPEG/PNG)", 
        type=["png", "jpg", "jpeg"],
        help="Upload a clear orthopedic radiograph image."
    )
    
    # 2. Text Input for Clinical Context
    patient_history = st.text_area(
        "Patient Clinical History & Symptoms", 
        height=100,
        placeholder="e.g., 54yo female, slipped on ice. Severe localized pain and swelling near the right distal radius. No prior fractures."
    )
    
    # 3. Text Input for Medications
    prescription = st.text_input(
        "Prescribed Medication & Dosage", 
        placeholder="e.g., Ibuprofen 600mg PO TID, Tramadol 50mg PRN"
    )
    
    # Preview Image if uploaded
    if uploaded_file:
        st.info(" X-Ray Image Preview:")
        st.image(uploaded_file, use_container_width=True)

with col2:
    st.subheader(" Clinical AI Analysis")
    
    # Action Button
    if st.button(" Analyze Case & Validate Safety", type="primary"):
        if not uploaded_file:
            st.error("Please upload an X-ray image before running the analysis.")
        elif not prescription.strip():
            st.warning("Please input the prescribed medication to execute safety validation.")
        else:
            with st.spinner("Processing medical vision features and evaluating drug safety interactions..."):
                try:
                    # Construct multipart form-data payload for FastAPI
                    files = {
                        "file": (uploaded_file.name, uploaded_file.getvalue(), uploaded_file.type)
                    }
                    data = {
                        "prescription": prescription,
                        "patient_history": patient_history
                    }
                    
                    # Make POST request to FastAPI endpoint
                    backend_url = "http://127.0.0.1:8000/api/v1/validate-case"
                    response = requests.post(backend_url, files=files, data=data, timeout=60)
                    
                    if response.status_code == 200:
                        result = response.json()
                        st.success("Analysis Complete!")
                        # Render the markdown clinical report generated by the LLM
                        st.markdown(result["report"])
                    else:
                        st.error(f"Backend API Error: {response.status_code} - {response.text}")
                        
                except requests.exceptions.ConnectionError:
                    st.error("Could not connect to the FastAPI backend. Is your server running on port 8000?")
                except Exception as e:
                    st.error(f"An unexpected error occurred: {str(e)}")
                    
    else:
        # Placeholder message before analysis runs
        st.info("Fill out the input panel on the left and click 'Analyze Case' to generate the diagnostic validation report.")